### PR TITLE
Fixing Search Bug

### PR DESCRIPTION
**Pull request by lasnikprogram**
I have no idea how I found this bug this early but when lowering the view distance while having search enabled will cause some blocks to never get deleted. This is fixed.

**Also a suggestion: Maybe make a setting in which you can change the distance blocks get searched or at least a slider to regulate the maximum amount of shown blocks. (In the current state searching in the Nether for these gold blocks is just impossible)**

### CODE REVIEW

**Comment by BleachDrinker420** [comment]
` || (oldViewDistance != mc.options.viewDistance && oldViewDistance != -1)`
should just be
` || oldViewDistance != mc.options.viewDistance`

dababy convertible

**Comment by lasnikprogram** [comment]
Oh. It´s beause I first tried something different

**Comment by lasnikprogram** [comment]
wth is CodeFactors problem

**Comment by BleachDrinker420** [comment]
wrong button

**Pull request merged**
