### PR TITLE
Update Module.java

### PR DESCRIPTION
**Pull request by VeryWeirdUser**

### CODE REVIEW

**Review by vil — APPROVED** [review]
I approve, this has to be merged instantly!!!!!!!!

**Comment by VeryWeirdUser** [comment]
Also I guess module category could be final

**Comment by BleachDev** [comment]
This truly is important stuff

**Comment by VeryWeirdUser** [comment]
> This truly is important stuff

Sarcasm?

**Comment by BleachDev** [comment]
Yes, this is the silliest pull request I've ever seen
(And i stopped working on BleachHack quite a while ago so i'm probably not gonna merge it)

**Comment by VeryWeirdUser** [comment]
> Yes, this is the silliest pull request I've ever seen
> 
> (And i stopped working on BleachHack quite a while ago so i'm probably not gonna merge it)

Are you going to archive this project, or give ownership to anyone else?

**Pull request closed without merging**
