### PR TITLE
Fixed notebot

### PR DESCRIPTION
**Pull request by DarkReaper231**
I fixed Notebot Stealer because it wasn't saving songs in txt files when disabled.

Also I added itemlist command which I added into epearl back when BleachHack was dead for a while but since this repo is now way more updated, I would rather use this one and have this one feature here.

What it does:
When you execute itemlist command, a txt file is created containing every single item ID loaded in the game. This is handy for devs I guess. I used it few times for disabling specific blocks and items in World Guard.

### CODE REVIEW

**Comment by BleachDrinker420** [comment]
I don't see the point of $infolist, its way too specific and not very useful, something like $export ... would probably be better,
Also i'd not dump files into the main bleach directory because then it gets really cluttered

**Review by DarkReaper231 — COMMENTED** [review]
I removed itemlist and kept just the Notebot fix

**Comment by BleachDrinker420** [comment]
I'll merge it and catch up on the new issues when i'm done with moveable ui

**Comment by BleachDrinker420** [comment]
Implemented in https://github.com/BleachDrinker420/BleachHack/commit/f089ed25a157618b1c75e7f63aecf56d84dfaf05

**Pull request closed without merging**
