### PR TITLE
Cock and ball torture

### LINKED ISSUE #353: [Bug] when GUI key is bound to a letter, trying to type that letter into the email/pass box opens the gui
This should be an easy fix, just before you open the ClickGUI when in the main menu, check if the user is typing in a text box.

This would make it to when someone has the ClickGUI bound to something like Y, it would make it to where they can type Y into the text box without opening the ClickGUI, making typing that letter impossible.

### PR DESCRIPTION
**Pull request by TheAirBlow**
Current changelog:
* fcf4445: Add init method to modules
* fcf4445: Add DisableBleach module
* fcf4445: Add unloadModule method
* 080858e: Fix warnings on IntelliJ (replace "%s" with "{}")
* 71fd36a: Mother Russia toggle in BetterChat
* 8459272: The Altening support (definetly not stolen from #348) 
* 75f174c: Cobweb AntiFall mode (#155)
* feaaf4c: Fix #353
* 3039fdc: Implement #321

Tested: `No`
Status: `Draft`

### CODE REVIEW

**Comment by BleachDrinker420** [comment]
agreed, this really is a cock and ball torture moment

**Comment by BleachDrinker420** [comment]
bruh

**Comment by TheAirBlow** [comment]
image

**Comment by BleachDrinker420** [comment]
please split the pull requests up cause i'm not gonna add half these features and the other half needs serious rewriting to make them acceptable quality

**Comment by TheAirBlow** [comment]
gotta do it somehow

**Comment by TheAirBlow** [comment]
Needs to be split

**Pull request closed without merging**
