### PR TITLE
InventoryViewer to UI

### PR DESCRIPTION
**Pull request by HerraVp**
Joe ??????????????????????????????????????????????????????????????????????????????????????????????

### CODE REVIEW

**Comment by BleachDrinker420** [comment]
using outdated ui class
crningeng

**Comment by BleachDrinker420** [comment]
update then i'll consider merging

**Comment by HerraVp** [comment]
> 
> 
> update then i'll consider merging

:obama: moment

Yeah i'll do it when im at home. kekw

**Comment by HerraVp** [comment]
Ima close this obama now and open a new one soon.

**Pull request closed without merging**
