### PR TITLE
Fixing bleachs mistakes

### PR DESCRIPTION
**Pull request by lasnikprogram**
Imagine creating an Event which you never actually use. Kinda cringe

### CODE REVIEW

**Comment by lasnikprogram** [comment]
wait what. Why did it fail? :(

**Comment by BleachDrinker420** [comment]
wtf, i swear i used this event

**Comment by BleachDrinker420** [comment]
and it failed because you didn't remove the imports from xray

**Comment by lasnikprogram** [comment]
oops

**Pull request merged**
