### PR TITLE
Add 3 important haha funny obama approved game breaking modules aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 

### PR DESCRIPTION
**Pull request by vil**
merge this game changing pull request!!!! because why not :troll: #291

### CODE REVIEW

**Comment by BleachDev** [comment]
people on default resolution can't even have 6 tabs open at the same time

**Comment by vil** [comment]
travis-scott-travis-scott-apology

**Comment by Doogie13** [comment]
make derp edit packets sent rather than sending new ones so it doesnt rubberband all over the place

**Comment by master7720** [comment]
why add bloat modules

**Comment by vil** [comment]
Why tf is this still here.
 IglglgkfhdgCsvzvzvzvdhdhsydydudjdjdjdydywtwtshshsjdjzjzbxnxnxfjdhshjdhdhtagtqtaaaaaaaaaaaaaaaaaaaa

**Pull request closed without merging**
