### PR TITLE
Added an Auto Jump on an edge of a block

### PR DESCRIPTION
**Pull request by lasnikprogram**
This hack makes you jump when you walk over an edge of a block.

### CODE REVIEW

**Comment by BleachDrinker420** [comment]
Rename it to AutoParkour, i'll merge it later and add a few features to it

**Comment by lasnikprogram** [comment]
Sorry. Didn´t mean to close just renamed my branch because of a typo :,(
I´ll make a new one with your request in a few minutes

**Comment by MorganAnkan** [comment]
isnt there already a autojump in minecraft? ;P

**Comment by MorganAnkan** [comment]
oh nvm i see what it does now

**Pull request closed without merging**
